language: bash

# services:
#   - docker

# before_install:
#   - docker run --rm --privileged multiarch/qemu-user-static:register --reset

# 构建版本需求
env: 
  - CORE=amd64 PY=3.7 LIB=pytorch
#   - CORE=arm64 PY=3.8 LIB=pyhdfs

# 运行构建调度脚本
script:
#   - ./tools/run-in-woker.sh
  - chmod +x ./builds/pytorch.sh && ./builds/pytorch.sh

# 上传结果到 github release
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "philogag"
  - git config --local user.email "philogag@qq.com"
  # - export TRAVIS_TAG=${TRAVIS_TAG:-$LIB-$(git log --format=%h -1)}
  - export TRAVIS_TAG=${TRAVIS_TAG:-$LIB}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file: /opt/export/zips/*
  skip_cleanup: true
  overwrite: true
